title: Abigail Neely
logo: /assets/img/logo-cropped.png

description: Computer Science and Technology Resume
# show_downloads: true
theme: jekyll-theme-minimal

author:
  name: Abby Neely
  url: http://abbyduck.github.com
