title: Abigail Neely
logo: /assets/img/abigail-neely.png

description: Computer Science and Technology Resume <br/><br/> <a href="https://github.com/AbbyDuhDuck">View My Actual GitHub Profile</a>
# show_downloads: true
theme: jekyll-theme-minimal

author:
  name: Abby Neely
  url: http://abbyduck.github.com
