title: Abigail Neely
logo: /assets/img/logo-cropped.png

description: Computer Science and Technology Resume <br/> <a href="https://github.com/AbbyDuhDuck">Visit My Actual GitHub Profile</a>
# show_downloads: true
theme: jekyll-theme-minimal

author:
  name: Abby Neely
  url: http://abbyduck.github.com
